replicaCount: 2

service:
  type: ClusterIP
  port: 80

containerPorts:
  http: 8080

ingress:
  enabled: false

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 200m
